spring:
  application:
    name: api-gateway-service
  cloud:
    gateway:
      routes:
        - id: book-ticket-service
          uri: lb://BOOK-TICKET-SERVICE
          predicates:
            - Path=/booking/**
        - id: payment-service
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/payment/**